[tool.poetry]
name = "project-name"
version = "0.1.0"
description = ""
authors = ["YuerWangg <143535000+YuerWangg@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
